### ISSUE TITLE
Dlib: not a supported wheel on this platform

### ISSUE THREAD

**Issue by LucasNiesen** [datamagic2020/Install-dlib#3]
Hello

I have python 3.8.2 and i downloaded **dlib-19.22.99-cp310-cp310-win_amd64.whl**.
When i run `pip install dlib-19.22.99-cp310-cp310-win_amd64.whl` i get this error `ERROR: dlib-19.22.99-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.`

Does anybody know why i get this error and how i can fix this?

**Comment by mahmoud98-30** [comment]
You should install:
 pip install " PATH OF FILE/ dlib-19.22.99-cp38-cp38-win_amd64.whl "

Because you use python 3.8

**Comment by LucasNiesen** [comment]
> You should install: pip install " PATH OF FILE/ dlib-19.22.99-cp38-cp38-win_amd64.whl "
> 
> Because you use python 3.8

I tried it but i got the same issue. `pip install "G:\Gedeelde drives\4TW_2022-2023_T1(Lucas-Bram-Senne)\Lucas N\Test gezichtsherkenning\dlib-19.19.0-cp38-cp38-win_amd64.whl`

**Comment by mahmoud98-30** [comment]
try `pip install "G:/Gedeelde drives/4TW_2022-2023_T1(Lucas-Bram-Senne)/Lucas N/Test gezichtsherkenning/dlib-19.19.0-cp38-cp38-win_amd64.whl"`

and make sure your windows is 64

**Comment by mahmoud98-30** [comment]
[maybe help you](https://github.com/datamagic2020/Install-dlib)

**Comment by LucasNiesen** [comment]
> pip install "G:/Gedeelde drives/4TW_2022-2023_T1(Lucas-Bram-Senne)/Lucas N/Test gezichtsherkenning/dlib-19.19.0-cp38-cp38-win_amd64.whl"

Same problem
